server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:testdb;AUTO_RECONNECT=TRUE;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8081/realms/tutorial-service-realm"